import type { GoalTemplate } from './goal.types';

/**
 * Catalogue statique des templates d'objectifs V1.
 *
 * `frequency` est volontairement simple (`daily` | `weekly` | `as_needed`).
 * Plus tard, on pourra affiner avec une notion du type `timesPerWeek` pour
 * exprimer « 3 séances par semaine » sans surcharger le modèle en V1.
 */

export const athleticTemplate: GoalTemplate = {
  id: 'template-sport-athletic',
  category: 'sport',
  title: 'Devenir plus athlétique',
  description:
    'Construire force, mobilité et récupération avec des actions quotidiennes réalistes.',
  suggestedLevel: 'intermediate',
  defaultActions: [
    {
      id: 'template-sport-athletic-strength-session',
      goalCategory: 'sport',
      title: 'Séance muscu',
      description: 'Séance de musculation guidée avec exercices et séries à enregistrer.',
      taskKind: 'strength',
      defaultDurationMinutes: 45,
      frequency: 'weekly',
      difficulty: 'hard',
      energyRequired: 'high',
      tags: ['strength', 'workout'],
    },
    {
      id: 'template-sport-athletic-mobility-short',
      goalCategory: 'sport',
      title: 'Mobilité courte',
      description: 'Routine express pour débloquer les articulations avant ou après l’effort.',
      taskKind: 'timer',
      defaultDurationMinutes: 10,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['mobility', 'recovery'],
    },
    {
      id: 'template-sport-athletic-weigh-in',
      goalCategory: 'sport',
      title: 'Pesée',
      description: 'Noter le poids du jour pour suivre l’évolution sur la durée.',
      taskKind: 'simple',
      defaultDurationMinutes: 2,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['tracking', 'body'],
    },
    {
      id: 'template-sport-athletic-protein-meal',
      goalCategory: 'sport',
      title: 'Repas protéiné',
      description: 'Préparer un repas riche en protéines pour soutenir la récupération.',
      taskKind: 'recipe',
      defaultDurationMinutes: 20,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['nutrition', 'protein'],
    },
    {
      id: 'template-sport-athletic-quick-review',
      goalCategory: 'sport',
      title: 'Bilan rapide',
      description: 'Faire le point sur la semaine : énergie, séances réalisées, prochaine étape.',
      taskKind: 'steps',
      defaultDurationMinutes: 5,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['review', 'weekly'],
    },
  ],
};

export const mobilityTemplate: GoalTemplate = {
  id: 'template-mobility',
  category: 'mobility',
  title: 'Améliorer ma mobilité',
  description:
    'Gagner en souplesse et en confort articulaire avec des routines courtes et régulières.',
  suggestedLevel: 'beginner',
  defaultActions: [
    {
      id: 'template-mobility-morning-routine',
      goalCategory: 'mobility',
      title: 'Routine mobilité matin',
      description: 'Enchaînement guidé au réveil pour préparer le corps à la journée.',
      taskKind: 'timer',
      defaultDurationMinutes: 15,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['morning', 'routine'],
    },
    {
      id: 'template-mobility-express',
      goalCategory: 'mobility',
      title: 'Mobilité express',
      description: 'Session ultra-courte à glisser entre deux activités.',
      taskKind: 'timer',
      defaultDurationMinutes: 5,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['express', 'break'],
    },
    {
      id: 'template-mobility-breathing',
      goalCategory: 'mobility',
      title: 'Respiration',
      description: 'Exercice de respiration pour relâcher tensions et améliorer la posture.',
      taskKind: 'timer',
      defaultDurationMinutes: 5,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['breathing', 'relaxation'],
    },
    {
      id: 'template-mobility-hips-ankles',
      goalCategory: 'mobility',
      title: 'Étirement hanches / chevilles',
      description: 'Focus sur hanches et chevilles, zones souvent raides au quotidien.',
      taskKind: 'timer',
      defaultDurationMinutes: 10,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['hips', 'ankles', 'stretch'],
    },
  ],
};

export const nutritionTemplate: GoalTemplate = {
  id: 'template-nutrition',
  category: 'nutrition',
  title: 'Mieux manger',
  description: 'Structurer l’alimentation avec des repas simples, équilibrés et faciles à tenir.',
  suggestedLevel: 'intermediate',
  defaultActions: [
    {
      id: 'template-nutrition-protein-breakfast',
      goalCategory: 'nutrition',
      title: 'Petit déjeuner protéiné',
      description: 'Commencer la journée avec un petit-déjeuner nourrissant et rassasiant.',
      taskKind: 'recipe',
      defaultDurationMinutes: 20,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['breakfast', 'protein'],
    },
    {
      id: 'template-nutrition-balanced-lunch',
      goalCategory: 'nutrition',
      title: 'Déjeuner équilibré',
      description:
        'Composer un déjeuner avec légumes, protéines et féculents en proportions simples.',
      taskKind: 'recipe',
      defaultDurationMinutes: 25,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['lunch', 'balanced'],
    },
    {
      id: 'template-nutrition-meal-prep',
      goalCategory: 'nutrition',
      title: 'Préparation repas',
      description: 'Préparer à l’avance les repas de la semaine pour réduire la charge mentale.',
      taskKind: 'steps',
      defaultDurationMinutes: 30,
      frequency: 'weekly',
      difficulty: 'medium',
      energyRequired: 'medium',
      tags: ['meal-prep', 'planning'],
    },
    {
      id: 'template-nutrition-hydration',
      goalCategory: 'nutrition',
      title: 'Hydratation',
      description: 'Vérifier et compléter l’hydratation tout au long de la journée.',
      taskKind: 'simple',
      defaultDurationMinutes: 2,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['hydration', 'health'],
    },
    {
      id: 'template-nutrition-simple-tracking',
      goalCategory: 'nutrition',
      title: 'Suivi simple',
      description: 'Noter brièvement ce qui a bien fonctionné côté alimentation cette semaine.',
      taskKind: 'simple',
      defaultDurationMinutes: 3,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['tracking', 'review'],
    },
  ],
};

export const developmentTemplate: GoalTemplate = {
  id: 'template-learning-dev',
  category: 'learning',
  title: 'Progresser en développement',
  description:
    'Avancer régulièrement en apprentissage technique et en pratique sur un projet concret.',
  suggestedLevel: 'intermediate',
  defaultActions: [
    {
      id: 'template-learning-dev-study-session',
      goalCategory: 'learning',
      title: 'Session apprentissage 45 min',
      description: 'Bloc dédié à la théorie ou à un tutoriel, avec objectif clair pour la session.',
      taskKind: 'learning',
      defaultDurationMinutes: 45,
      frequency: 'daily',
      difficulty: 'medium',
      energyRequired: 'medium',
      tags: ['study', 'theory'],
    },
    {
      id: 'template-learning-dev-project-practice',
      goalCategory: 'learning',
      title: 'Pratique projet',
      description:
        'Mettre en application ce qui vient d’être appris sur un petit exercice ou feature.',
      taskKind: 'learning',
      defaultDurationMinutes: 30,
      frequency: 'daily',
      difficulty: 'medium',
      energyRequired: 'medium',
      tags: ['practice', 'project'],
    },
    {
      id: 'template-learning-dev-synthesis-note',
      goalCategory: 'learning',
      title: 'Note de synthèse',
      description: 'Résumer en quelques lignes ce qui a été compris et ce qu’il reste à clarifier.',
      taskKind: 'simple',
      defaultDurationMinutes: 10,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['notes', 'synthesis'],
    },
    {
      id: 'template-learning-dev-review',
      goalCategory: 'learning',
      title: 'Révision',
      description: 'Repasser sur les notes et concepts de la semaine pour ancrer les acquis.',
      taskKind: 'learning',
      defaultDurationMinutes: 20,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['review', 'spaced-repetition'],
    },
  ],
};

export const spiritualityTemplate: GoalTemplate = {
  id: 'template-spirituality',
  category: 'spirituality',
  title: 'Routine spirituelle',
  description:
    'Ancrer une pratique spirituelle régulière, simple et compatible avec le rythme du jour.',
  suggestedLevel: 'intermediate',
  defaultActions: [
    {
      id: 'template-spirituality-morning-tefila',
      goalCategory: 'spirituality',
      title: 'Tefila du matin',
      description: 'Moment de prière du matin, guidé étape par étape selon la routine choisie.',
      taskKind: 'spiritual',
      defaultDurationMinutes: 30,
      frequency: 'daily',
      difficulty: 'medium',
      energyRequired: 'medium',
      tags: ['tefila', 'morning'],
    },
    {
      id: 'template-spirituality-intention',
      goalCategory: 'spirituality',
      title: 'Moment d’intention',
      description: 'Pause courte pour fixer une intention consciente pour la journée.',
      taskKind: 'spiritual',
      defaultDurationMinutes: 10,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['intention', 'mindfulness'],
    },
    {
      id: 'template-spirituality-personal-note',
      goalCategory: 'spirituality',
      title: 'Note personnelle courte',
      description: 'Noter une réflexion, une gratitude ou un apprentissage du jour.',
      taskKind: 'simple',
      defaultDurationMinutes: 5,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['journal', 'reflection'],
    },
  ],
};

export const personalProjectTemplate: GoalTemplate = {
  id: 'template-personal-project',
  category: 'project',
  title: 'Avancer sur un projet personnel',
  description: 'Découper un projet en actions concrètes pour avancer sans se disperser.',
  suggestedLevel: 'intermediate',
  defaultActions: [
    {
      id: 'template-personal-project-daily-priority',
      goalCategory: 'project',
      title: 'Tâche prioritaire du jour',
      description: 'Identifier et attaquer la seule tâche qui fait vraiment avancer le projet.',
      taskKind: 'steps',
      defaultDurationMinutes: 30,
      frequency: 'daily',
      difficulty: 'medium',
      energyRequired: 'medium',
      tags: ['priority', 'daily'],
    },
    {
      id: 'template-personal-project-focus-block',
      goalCategory: 'project',
      title: 'Bloc focus',
      description: 'Session de travail profond sans interruption sur une partie du projet.',
      taskKind: 'timer',
      defaultDurationMinutes: 45,
      frequency: 'weekly',
      difficulty: 'hard',
      energyRequired: 'high',
      tags: ['focus', 'deep-work'],
    },
    {
      id: 'template-personal-project-follow-up',
      goalCategory: 'project',
      title: 'Relance / suivi',
      description: 'Faire le point sur les blocages, relances ou décisions en attente.',
      taskKind: 'simple',
      defaultDurationMinutes: 10,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['follow-up', 'admin'],
    },
    {
      id: 'template-personal-project-mini-review',
      goalCategory: 'project',
      title: 'Mini bilan',
      description: 'Bilan rapide de la semaine : avancées, obstacles et prochaine priorité.',
      taskKind: 'steps',
      defaultDurationMinutes: 5,
      frequency: 'weekly',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['review', 'weekly'],
    },
  ],
};

export const sleepTemplate: GoalTemplate = {
  id: 'template-sleep',
  category: 'sleep',
  title: 'Améliorer mon sommeil',
  description: 'Installer une routine du soir pour mieux s’endormir et mieux récupérer.',
  suggestedLevel: 'beginner',
  defaultActions: [
    {
      id: 'template-sleep-evening-routine',
      goalCategory: 'sleep',
      title: 'Routine soir',
      description:
        'Enchaînement calme avant le coucher : préparation, détente, signal de fin de journée.',
      taskKind: 'steps',
      defaultDurationMinutes: 20,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['evening', 'routine'],
    },
    {
      id: 'template-sleep-screen-cutoff',
      goalCategory: 'sleep',
      title: 'Couper écrans',
      description:
        'Arrêter les écrans à l’heure prévue pour laisser le corps se préparer au sommeil.',
      taskKind: 'simple',
      defaultDurationMinutes: 5,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['screens', 'wind-down'],
    },
    {
      id: 'template-sleep-next-day-prep',
      goalCategory: 'sleep',
      title: 'Préparation lendemain',
      description: 'Préparer le minimum pour le lendemain et alléger la charge mentale au réveil.',
      taskKind: 'steps',
      defaultDurationMinutes: 10,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['planning', 'evening'],
    },
    {
      id: 'template-sleep-quality-note',
      goalCategory: 'sleep',
      title: 'Note qualité sommeil',
      description: 'Noter brièvement la qualité du sommeil et ce qui a aidé ou gêné.',
      taskKind: 'simple',
      defaultDurationMinutes: 3,
      frequency: 'daily',
      difficulty: 'easy',
      energyRequired: 'low',
      tags: ['tracking', 'sleep-quality'],
    },
  ],
};

export const GOAL_TEMPLATES: GoalTemplate[] = [
  athleticTemplate,
  mobilityTemplate,
  nutritionTemplate,
  developmentTemplate,
  spiritualityTemplate,
  personalProjectTemplate,
  sleepTemplate,
];

export function getGoalTemplateById(id: string): GoalTemplate | undefined {
  return GOAL_TEMPLATES.find((template) => template.id === id);
}
